quarkus:
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s %X%e%n"
  devservices:
    enabled: false
  application:
    name: java-lobby-server
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    db-kind: mariadb
    username: ${DB_USERNAME:faf-python-server}
    password: ${DB_PASSWORD:banana}
    jdbc:
      url: ${DB_URL:jdbc:mariadb://localhost:3306/faf_lobby?ssl=false}
  http:
    port: 8003
    host-validation:
      allowed-hosts: ${ALLOWED_HOST:ws.faforever.localhost}

mp:
  jwt:
    verify:
      issuer: ${HYDRA_TOKEN_ISSUER:http://ory-hydra:4444}
      key-format: JWKS
      publickey:
        location: ${HYDRA_JWKS_URL:http://localhost:4444/.well-known/jwks.json}

"%test":
  quarkus:
    scheduler:
      enabled: false
    log:
      console:
        json:
          enabled: false
      category:
        "com.faforever":
          level: DEBUG
        "io.quarkus.websockets.next.traffic":
          level: DEBUG

"%dev":
  quarkus:
    live-reload:
      instrumentation: true
    log:
      console:
        json:
          enabled: false
      category:
        "com.faforever":
          level: DEBUG
        "io.quarkus.websockets.next.traffic":
          level: DEBUG
    websockets-next:
      server:
        traffic-logging:
          enabled: true
    hibernate-orm:
      log:
        sql: true
